### ISSUE TITLE
http://git.bytbox.net/sloc disappeared.

### ISSUE THREAD

**Issue by maruel** [bytbox/sloc#1]
go get git.bytbox.net/sloc.git/sloc doesn't work anymore as the repository cannot be found.

**Comment by bytbox** [comment]
Fixed. Thanks for pointing that out.

**Comment by maruel** [comment]
Sadly, it's not really fixed because go get generates:
package git.bytbox.net/sloc.git/sloc: cannot download, http://git.bytbox.net/sloc uses insecure protocol

and I can't pull from https://, if I reset the remote to https://, I get:
$ git fetch
fatal: unable to access 'https://git.bytbox.net/sloc/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

Why can't the github clone be kept up to date?

**Comment by bytbox** [comment]
Use -insecure, as per the docs.  Or, use git to download it directly.

**Comment by maruel** [comment]
To clarify my question; do you mean that you do not want people to be able to checkout your project using the default Go tooling?

**Comment by bytbox** [comment]
You can use the default go tooling, using the -insecure option.
